"""Where generated intelligence lands on disk.

Markdown is the human-readable view; SQLite is what the system queries. The
tree is generated state that grows on every run, so it lives outside the
repository by default -- the spec's `alena-intelligence/` layout, rooted at
~/.alena/intelligence unless ALENA_INTELLIGENCE_DIR says otherwise.
"""

from __future__ import annotations

import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

DEFAULT_INTELLIGENCE_DIR = "~/.alena/intelligence"

SUBDIRECTORIES = (
    "repositories",
    "research",
    "engineering/codex",
    "engineering/claude",
    "recommendations",
    "memory",
)


def intelligence_dir() -> Path:
    raw = os.getenv("ALENA_INTELLIGENCE_DIR") or DEFAULT_INTELLIGENCE_DIR
    return Path(raw).expanduser().resolve()


def ensure_layout(root: Optional[Path] = None) -> Path:
    root = root or intelligence_dir()
    for name in SUBDIRECTORIES:
        (root / name).mkdir(parents=True, exist_ok=True)
    return root


def repository_dir(repository_id: str, root: Optional[Path] = None) -> Path:
    path = (root or intelligence_dir()) / "repositories" / repository_id
    path.mkdir(parents=True, exist_ok=True)
    return path


def _bullets(items: List[str], empty: str = "_none_") -> str:
    return "\n".join(f"- {item}" for item in items) if items else empty


def render_profile(scan: Dict[str, Any]) -> str:
    """The repository profile, as a human reads it."""
    languages = scan.get("languages") or {}
    dependencies = scan.get("dependencies") or []
    todos = scan.get("todos") or []
    delta = scan.get("todo_delta") or {}
    commits = scan.get("recent_commits") or []

    by_ecosystem: Dict[str, List[str]] = {}
    for dependency in dependencies:
        by_ecosystem.setdefault(dependency["ecosystem"], []).append(dependency["name"])

    dependency_block = "\n\n".join(
        f"**{ecosystem}** ({len(names)})\n\n{_bullets(sorted(names)[:60])}"
        for ecosystem, names in sorted(by_ecosystem.items())
    ) or "_none found_"

    marker_counts: Dict[str, int] = {}
    for todo in todos:
        marker_counts[todo["marker"]] = marker_counts.get(todo["marker"], 0) + 1

    lines = [
        f"# {scan.get('name', scan['repository_id'])}",
        "",
        "_Generated by ALENA. Edits here are overwritten on the next scan._",
        "",
        "| | |",
        "|---|---|",
        f"| Scanned | {scan.get('scanned_at', '')} |",
        f"| Branch | `{scan.get('branch') or 'unknown'}` |",
        f"| HEAD | `{(scan.get('head_sha') or 'none')[:12]}` |",
        f"| Working tree | {'dirty' if scan.get('dirty') else 'clean'} |",
        f"| Tracked files | {scan.get('file_count', 0)} |",
        f"| Workspace | `{scan.get('workspace', '')}` |",
        "",
    ]

    if scan.get("summary"):
        lines += ["## Summary", "", scan["summary"], ""]

    if scan.get("diff_summary"):
        lines += ["## Since the previous scan", "", scan["diff_summary"], ""]

    lines += [
        "## Languages",
        "",
        _bullets(
            [
                f"{name} — {count} file{'s' if count != 1 else ''}"
                for name, count in languages.items()
            ]
        ),
        "",
        "## Dependencies",
        "",
        dependency_block,
        "",
        "## TODO / FIXME",
        "",
        _bullets(
            [f"{marker}: {count}" for marker, count in sorted(marker_counts.items())],
            "_none_",
        ),
        "",
    ]

    if delta.get("added"):
        lines += [
            "### Appeared since the previous scan",
            "",
            _bullets(
                [
                    f"`{t['path']}:{t['line']}` — {t['marker']} {t['text']}".rstrip()
                    for t in delta["added"][:40]
                ]
            ),
            "",
        ]
    if delta.get("resolved"):
        lines += [
            "### Resolved since the previous scan",
            "",
            _bullets(
                [f"`{t['path']}` — {t['marker']} {t['text']}".rstrip() for t in delta["resolved"][:40]]
            ),
            "",
        ]

    lines += [
        "## Recent commits",
        "",
        _bullets([f"`{c['sha'][:8]}` {c['subject']} — {c['author']}" for c in commits[:20]]),
        "",
    ]
    return "\n".join(lines).rstrip() + "\n"


def write_profile(scan: Dict[str, Any], root: Optional[Path] = None) -> Path:
    path = repository_dir(scan["repository_id"], root) / "profile.md"
    path.write_text(render_profile(scan))
    return path


def utcnow() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")
